[package]
name = "ili9341-buffered"
version = "0.3.0-beta.1"
description = "A platform agnostic driver to interface with the ILI9341 (ald ILI9340C) TFT LCD display"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["embedded-hal-driver", "display", "LCD"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/gabrielzach/ili9341-rs"
edition = "2018"


[dependencies]
embedded-hal = "0.2.3"

[dependencies.embedded-graphics]
optional = true
version = "0.5.2"

[features]
default = ["graphics"]
graphics = ["embedded-graphics"]
